# Generated by Django 4.1.7 on 2023-04-06 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_remove_post_author_remove_post_created_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='qr_codes/')),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
